Repository cs361-stock-prediction/stock-predictor, pull requests merged in 2020-03, with the labels that each got.

#9 Adding attributions and Testing Merges. Fixes #8
  README.md
Labels: enhancement

#10 Merge basic HTML into server branch
  app/templates/base.html
  public/logo.png
  public/site.css
Labels: task

#12 Create main linter workflow
  .github/workflows/main.yml
Labels: enhancement, task

#13 Client Server Framework
  .github/workflows/.eslintrc.json
  .github/workflows/main.yml
  .gitignore
  README.md
  images/googlestock.png
  package.json
  scripts/install_requirements.sh
  server/server.py
  server/static/base.css
  server/static/index.css
  server/static/logo.svg
  server/templates/base.html
  server/templates/index.html
  start.sh
Labels: task

#16 Exclude Flake8 Error Classes
  .github/workflows/main.yml
Labels: bug

#14 Favicon Addition
  server/code.txt
  server/favicon-16x16.png
  server/favicon-32x32.png
  server/favicon.ico
  server/server.py
  server/static/favicon-16x16.png
  server/static/favicon-32x32.png
  server/static/favicon.ico
  server/static/logo.png
Labels: enhancement

#24 Adding Page Name Changes
  server/server.py
  server/templates/accounts.html
Labels: bug

#26 Login implementation
  scripts/install_requirements.sh
  server/server.py
  server/static/base.css
  server/static/createacct.css
  server/static/index.js
  server/static/login.css
  server/static/login.js
  server/static/search.js
  server/templates/accounts.html
  server/templates/base.html
  server/templates/createacct.html
  server/templates/login.html
Labels: enhancement, task

#35 User database & restructure
  .github/workflows/main.yml
  .gitignore
  config.py
  migrations/README
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/85ce456cafe9_create_userinfo_table.py
  predictor.py
  scripts/install_requirements.sh
  server/__init__.py
  server/forms.py
  server/models.py
  server/routes.py
  server/server.py
  server/templates/createacct.html
  server/templates/login.html
  start.sh
Labels: enhancement, task

#36 Account creation and login
  server/__init__.py
  server/forms.py
  server/models.py
  server/routes.py
  server/static/base.css
  server/templates/base.html
  server/templates/createacct.html
Labels: enhancement, task

#39 Create server_start.yml
  .github/workflows/server_start.yml
  scripts/install_requirements.sh
  scripts/requirements.txt
  start.sh
Labels: enhancement

#41 Fast Forwarding adding-stock-graphs to master
  scripts/install_requirements.sh
  scripts/requirements.txt
  server/static/prediction.css
  start.sh
Labels: enhancement

#42 Adding stock graphs
  config.py
  scripts/requirements.txt
  server/models.py
  server/routes.py
  server/static/prediction.js
  server/templates/prediction.html
Labels: task
